//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: GwRsMessages.proto
namespace U5ki.Infrastructure
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GwTlfRs")]
  public partial class GwTlfRs : global::ProtoBuf.IExtensible
  {
    public GwTlfRs() {}
    
    private U5ki.Infrastructure.GwTlfRs.State _St;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"St", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public U5ki.Infrastructure.GwTlfRs.State St
    {
      get { return _St; }
      set { _St = value; }
    }
    private uint _Priority;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Priority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Priority
    {
      get { return _Priority; }
      set { _Priority = value; }
    }
    private uint _CallBegin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"CallBegin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint CallBegin
    {
      get { return _CallBegin; }
      set { _CallBegin = value; }
    }
    private uint _Type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private string _GwIp = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"GwIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GwIp
    {
      get { return _GwIp; }
      set { _GwIp = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"State")]
    public enum State
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Idle", Value=0)]
      Idle = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BusyInterruptionAllow", Value=1)]
      BusyInterruptionAllow = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BusyInterruptionNotAllow", Value=2)]
      BusyInterruptionNotAllow = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NotAvailable", Value=3)]
      NotAvailable = 3
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GwLcRs")]
  public partial class GwLcRs : global::ProtoBuf.IExtensible
  {
    public GwLcRs() {}
    

    private string _GwIp = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"GwIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string GwIp
    {
      get { return _GwIp; }
      set { _GwIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GwRdRs")]
  public partial class GwRdRs : global::ProtoBuf.IExtensible
  {
    public GwRdRs() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}