//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMI.CD40.Module.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HMI.CD40.Module.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actividad en curso.
        /// </summary>
        internal static string ActivityError {
            get {
                return ResourceManager.GetString("ActivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dispositivo de audio no disponible: .
        /// </summary>
        internal static string AudioViaNotAvailable {
            get {
                return ResourceManager.GetString("AudioViaNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número erróneo.
        /// </summary>
        internal static string BadNumberError {
            get {
                return ResourceManager.GetString("BadNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Falsa maniobra.
        /// </summary>
        internal static string BadOperation {
            get {
                return ResourceManager.GetString("BadOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en dispositivo.
        /// </summary>
        internal static string DeviceError {
            get {
                return ResourceManager.GetString("DeviceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Frecuencia implicada en grupo de retransmisión.
        /// </summary>
        internal static string FrecuencyRtxError {
            get {
                return ResourceManager.GetString("FrecuencyRtxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auriculares.
        /// </summary>
        internal static string Headphones {
            get {
                return ResourceManager.GetString("Headphones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altavoz ocupado por linea caliente.
        /// </summary>
        internal static string LCSpeakerBusy {
            get {
                return ResourceManager.GetString("LCSpeakerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de máximo de participantes en conferencia.
        /// </summary>
        internal static string MaxConferenceNumber {
            get {
                return ResourceManager.GetString("MaxConferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay jacks.
        /// </summary>
        internal static string NoJacksError {
            get {
                return ResourceManager.GetString("NoJacksError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo máximo en PTT.
        /// </summary>
        internal static string PttCheckedTimeOut {
            get {
                return ResourceManager.GetString("PttCheckedTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Imposible, PTT pulsado.
        /// </summary>
        internal static string PttPulsedError {
            get {
                return ResourceManager.GetString("PttPulsedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RTX no aceptada. Squelch en más de una frecuencia.
        /// </summary>
        internal static string RtxGroupSquelchError {
            get {
                return ResourceManager.GetString("RtxGroupSquelchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Altavoz.
        /// </summary>
        internal static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca un jack en cada par de conectores.
        /// </summary>
        internal static string SplitModeError {
            get {
                return ResourceManager.GetString("SplitModeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desconocido.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
