//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v80/MS.VSIPCC.v80/ms.practices.scsf.2007may/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace HMI.Presentation.Rabat.Views
{
	partial class HeaderView
	{
		/// <summary> 
		/// Required designer variable.
		/// </summary>
		private System.ComponentModel.IContainer components = null;

		/// <summary> 
		/// Clean up any resources being used.
		/// </summary>
		/// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				if (components != null)
					components.Dispose();
			}

			base.Dispose(disposing);
		}

		#region Component Designer generated code

		/// <summary> 
		/// Required method for Designer support - do not modify 
		/// the contents of this method with the code editor.
		/// </summary>
		private void InitializeComponent()
		{
            this.components = new System.ComponentModel.Container();
            this._MsgLB = new System.Windows.Forms.ListBox();
            this._InfoBT = new HMI.Model.Module.UI.HMIButton();
            this._TitleBT = new HMI.Model.Module.UI.HMIButton();
            this.pnlHora = new System.Windows.Forms.Panel();
            this._tbTime = new System.Windows.Forms.TextBox();
            this._TbDate = new System.Windows.Forms.TextBox();
            this._timeTimer = new System.Windows.Forms.Timer(this.components);
            this._BriefingBT = new HMI.Model.Module.UI.HMIButton();
            this._SplitUC = new HMI.Presentation.Rabat.UI.SplitUC();
            this._BrightnessUDB = new HMI.Presentation.Rabat.UI.UpDownButton();
            this._BuzzerUDB = new HMI.Presentation.Rabat.UI.UpDownButton();
            this.pnlHora.SuspendLayout();
            this.SuspendLayout();
            // 
            // _MsgLB
            // 
            this._MsgLB.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this._MsgLB.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._MsgLB.FormattingEnabled = true;
            this._MsgLB.ItemHeight = 15;
            this._MsgLB.Location = new System.Drawing.Point(454, 5);
            this._MsgLB.Name = "_MsgLB";
            this._MsgLB.SelectionMode = System.Windows.Forms.SelectionMode.None;
            this._MsgLB.Size = new System.Drawing.Size(163, 79);
            this._MsgLB.TabIndex = 5;
            // 
            // _InfoBT
            // 
            this._InfoBT.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this._InfoBT.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._InfoBT.Location = new System.Drawing.Point(395, 3);
            this._InfoBT.Margin = new System.Windows.Forms.Padding(3, 3, 3, 1);
            this._InfoBT.Name = "_InfoBT";
            this._InfoBT.Size = new System.Drawing.Size(54, 44);
            this._InfoBT.TabIndex = 2;
            this._InfoBT.Text = "INFO";
            this._InfoBT.Click += new System.EventHandler(this._InfoBT_Click);
            // 
            // _TitleBT
            // 
            this._TitleBT.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this._TitleBT.Cursor = System.Windows.Forms.Cursors.Default;
            this._TitleBT.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._TitleBT.ImageAlign = System.Drawing.ContentAlignment.TopCenter;
            this._TitleBT.ImageNormal = global::HMI.Presentation.Rabat.Properties.Resources.LogoONDA;
            this._TitleBT.Location = new System.Drawing.Point(10, 1);
            this._TitleBT.Name = "_TitleBT";
            this._TitleBT.Size = new System.Drawing.Size(115, 81);
            this._TitleBT.TabIndex = 4;
            this._TitleBT.Text = "RABAT";
            this._TitleBT.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this._TitleBT.Click += new System.EventHandler(this._TitleBT_Click);
            // 
            // pnlHora
            // 
            this.pnlHora.BackColor = System.Drawing.Color.LightGray;
            this.pnlHora.Controls.Add(this._tbTime);
            this.pnlHora.Controls.Add(this._TbDate);
            this.pnlHora.Location = new System.Drawing.Point(127, 3);
            this.pnlHora.Name = "pnlHora";
            this.pnlHora.Size = new System.Drawing.Size(73, 66);
            this.pnlHora.TabIndex = 6;
            // 
            // _tbTime
            // 
            this._tbTime.BackColor = System.Drawing.Color.White;
            this._tbTime.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._tbTime.Location = new System.Drawing.Point(4, 40);
            this._tbTime.Name = "_tbTime";
            this._tbTime.ReadOnly = true;
            this._tbTime.Size = new System.Drawing.Size(66, 20);
            this._tbTime.TabIndex = 1;
            this._tbTime.Text = "00:00:00";
            this._tbTime.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // _TbDate
            // 
            this._TbDate.BackColor = System.Drawing.Color.White;
            this._TbDate.Font = new System.Drawing.Font("Microsoft Sans Serif", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._TbDate.Location = new System.Drawing.Point(4, 5);
            this._TbDate.Name = "_TbDate";
            this._TbDate.ReadOnly = true;
            this._TbDate.Size = new System.Drawing.Size(66, 20);
            this._TbDate.TabIndex = 0;
            this._TbDate.Text = "00/00/00";
            this._TbDate.TextAlign = System.Windows.Forms.HorizontalAlignment.Center;
            // 
            // _timeTimer
            // 
            this._timeTimer.Enabled = true;
            this._timeTimer.Interval = 1000;
            this._timeTimer.Tick += new System.EventHandler(this._timerTimer_Tick);
            // 
            // _BriefingBT
            // 
            this._BriefingBT.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this._BriefingBT.Font = new System.Drawing.Font("Microsoft Sans Serif", 6F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this._BriefingBT.ImageNormal = global::HMI.Presentation.Rabat.Properties.Resources.boton_de_grabacion1;
            this._BriefingBT.Location = new System.Drawing.Point(395, 36);
            this._BriefingBT.Margin = new System.Windows.Forms.Padding(1);
            this._BriefingBT.Name = "_BriefingBT";
            this._BriefingBT.Size = new System.Drawing.Size(54, 46);
            this._BriefingBT.TabIndex = 7;
            this._BriefingBT.TextAlign = System.Drawing.ContentAlignment.BottomCenter;
            this._BriefingBT.Click += new System.EventHandler(this._BriefingBT_Click);
            // 
            // _SplitUC
            // 
            this._SplitUC.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Left)));
            this._SplitUC.BackColor = System.Drawing.Color.White;
            this._SplitUC.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this._SplitUC.JackOff = global::HMI.Presentation.Rabat.Properties.Resources.JackOff;
            this._SplitUC.JackOn = global::HMI.Presentation.Rabat.Properties.Resources.JackOn;
            this._SplitUC.Location = new System.Drawing.Point(201, 3);
            this._SplitUC.Margin = new System.Windows.Forms.Padding(0);
            this._SplitUC.Name = "_SplitUC";
            this._SplitUC.Size = new System.Drawing.Size(190, 79);
            this._SplitUC.TabIndex = 3;
            this._SplitUC.SplitSelectionClick += new System.EventHandler(this._SplitUC_SplitSelectionClick);
            this._SplitUC.SplitModeChanging += new Utilities.GenericEventHandler<HMI.Model.Module.BusinessEntities.SplitMode>(this._SplitUC_SplitModeChanging);
            this._SplitUC.Load += new System.EventHandler(this._SplitUC_Load);
            // 
            // _BrightnessUDB
            // 
            this._BrightnessUDB.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this._BrightnessUDB.BackColor = System.Drawing.Color.Transparent;
            this._BrightnessUDB.DownImage = global::HMI.Presentation.Rabat.Properties.Resources.BrightnessDown;
            this._BrightnessUDB.Location = new System.Drawing.Point(623, 3);
            this._BrightnessUDB.Name = "_BrightnessUDB";
            this._BrightnessUDB.Size = new System.Drawing.Size(85, 79);
            this._BrightnessUDB.TabIndex = 0;
            this._BrightnessUDB.UpImage = global::HMI.Presentation.Rabat.Properties.Resources.BrightnessUp;
            this._BrightnessUDB.LevelDown += new System.EventHandler(this._BrightnessUDB_LevelDown);
            this._BrightnessUDB.LevelUp += new System.EventHandler(this._BrightnessUDB_LevelUp);
            // 
            // _BuzzerUDB
            // 
            this._BuzzerUDB.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom)
                        | System.Windows.Forms.AnchorStyles.Right)));
            this._BuzzerUDB.BackColor = System.Drawing.Color.Transparent;
            this._BuzzerUDB.DownImage = global::HMI.Presentation.Rabat.Properties.Resources.BuzzerDown;
            this._BuzzerUDB.Location = new System.Drawing.Point(714, 3);
            this._BuzzerUDB.Name = "_BuzzerUDB";
            this._BuzzerUDB.Size = new System.Drawing.Size(85, 79);
            this._BuzzerUDB.TabIndex = 1;
            this._BuzzerUDB.UpImage = global::HMI.Presentation.Rabat.Properties.Resources.BuzzerUp;
            this._BuzzerUDB.LevelDown += new System.EventHandler(this._BuzzerUDB_LevelDown);
            this._BuzzerUDB.LevelUp += new System.EventHandler(this._BuzzerUDB_LevelUp);
            this._BuzzerUDB.LongClick += new System.EventHandler(this._BuzzerUDB_LongClick);
            // 
            // HeaderView
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Inherit;
            this.Controls.Add(this._BriefingBT);
            this.Controls.Add(this.pnlHora);
            this.Controls.Add(this._SplitUC);
            this.Controls.Add(this._BrightnessUDB);
            this.Controls.Add(this._BuzzerUDB);
            this.Controls.Add(this._MsgLB);
            this.Controls.Add(this._InfoBT);
            this.Controls.Add(this._TitleBT);
            this.Name = "HeaderView";
            this.Size = new System.Drawing.Size(800, 86);
            this.pnlHora.ResumeLayout(false);
            this.pnlHora.PerformLayout();
            this.ResumeLayout(false);

		}

		#endregion

		private HMI.Model.Module.UI.HMIButton _TitleBT;
		private HMI.Model.Module.UI.HMIButton _InfoBT;
		private System.Windows.Forms.ListBox _MsgLB;
		private HMI.Presentation.Rabat.UI.UpDownButton _BrightnessUDB;
		private HMI.Presentation.Rabat.UI.UpDownButton _BuzzerUDB;
		private HMI.Presentation.Rabat.UI.SplitUC _SplitUC;
        private System.Windows.Forms.Panel pnlHora;
        private System.Windows.Forms.TextBox _tbTime;
        private System.Windows.Forms.TextBox _TbDate;
        private System.Windows.Forms.Timer _timeTimer;
        private Model.Module.UI.HMIButton _BriefingBT;
	}
}

